
@url = http://localhost:8080/api/basicUsers/login




######
POST {{url}}/ HTTP/1.1
Content-Type: application/json

{
    "username": "testingNew",
 
    "password":"paswordchanged"
    
  
  }

###
