//URL
@url = http://localhost:8080/api/UserRole 

//Get all the Roles
GET {{url}} HTTP/1.1  

###
//Get particular role
GET {{url}}/1 HTTP/1.1

###
//Create new role
POST {{url}}/ HTTP/1.1
Content-Type: application/json

{
  "role_name": "Tester"
  
}

###
//Update the role
PUT {{url}}/1 HTTP/1.1
Content-Type: application/json

{
    "userRole_id": 1,
    "role_name": "Admin"
}

###
//delete the role
DELETE {{url}}/5 HTTP/1.1